package com.justrocketscience.auth.mapper;

import com.justrocketscience.auth.dto.request.RegisterRequest;
import com.justrocketscience.auth.dto.response.UserProfileResponse;
import com.justrocketscience.auth.entity.User;
import com.justrocketscience.auth.entity.UserRole;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mapstruct.factory.Mappers;

import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link UserMapper}.
 *
 * <h3>Testing strategy</h3>
 * MapStruct mappers are generated at compile time. These tests verify:
 * <ol>
 *   <li>Field values are correctly transferred between source and target</li>
 *   <li>Ignored fields are truly absent from the target</li>
 *   <li>Sensitive fields ({@code passwordHash}) are never populated by the mapper</li>
 *   <li>Type conversions (if any) produce correct values</li>
 * </ol>
 *
 * <p>No Spring context needed — {@code Mappers.getMapper()} instantiates the
 * generated implementation directly. Tests run in milliseconds.
 *
 * <h3>Why test generated code</h3>
 * MapStruct generates real Java code. If a field is renamed in the entity
 * but not in the mapper, the mapping silently produces null. These tests
 * catch that regression at the unit level, not after the API is deployed.
 * The most important test: {@code passwordHash_isNeverPopulated_byMapper}.
 */
class UserMapperTest {

    private final UserMapper mapper = Mappers.getMapper(UserMapper.class);

    // =========================================================================
    @Nested
    @DisplayName("toEntity — RegisterRequest → User")
    class ToEntity {

        @Test
        @DisplayName("maps username and email from request")
        void mapsUsernameAndEmail() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe",
                    "john@example.com",
                    "Password1!"
            );

            User user = mapper.toEntity(request);

            assertThat(user.getUsername()).isEqualTo("john_doe");
            assertThat(user.getEmail()).isEqualTo("john@example.com");
        }

        /**
         * THE most critical test in this class.
         * Verifies that the raw password from RegisterRequest is NEVER
         * copied to User.passwordHash by the mapper.
         * If this test fails, plaintext passwords could be persisted.
         */
        @Test
        @DisplayName("SECURITY: passwordHash is null after mapping — BCrypt encoding is service responsibility")
        void passwordHash_isNeverPopulated_byMapper() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe",
                    "john@example.com",
                    "Password1!"
            );

            User user = mapper.toEntity(request);

            assertThat(user.getPasswordHash())
                    .as("passwordHash must never be set by the mapper — service encodes it after mapping")
                    .isNull();
        }

        @Test
        @DisplayName("id is null after mapping — generated by DB")
        void id_isNull_afterMapping() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe", "john@example.com", "Password1!");

            User user = mapper.toEntity(request);

            assertThat(user.getId()).isNull();
        }

        @Test
        @DisplayName("role defaults to USER via @Builder.Default — not set by mapper")
        void role_defaultsToUser() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe", "john@example.com", "Password1!");

            User user = mapper.toEntity(request);

            // @Builder.Default on User.role = UserRole.USER
            // The mapper ignores role, so the default value is preserved
            assertThat(user.getRole()).isEqualTo(UserRole.USER);
        }

        @Test
        @DisplayName("isActive defaults to true via @Builder.Default — not set by mapper")
        void isActive_defaultsToTrue() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe", "john@example.com", "Password1!");

            User user = mapper.toEntity(request);

            assertThat(user.getIsActive()).isTrue();
        }

        @Test
        @DisplayName("createdAt and updatedAt are null — set by @PrePersist, not mapper")
        void timestamps_areNull_afterMapping() {
            RegisterRequest request = new RegisterRequest(
                    "john_doe", "john@example.com", "Password1!");

            User user = mapper.toEntity(request);

            assertThat(user.getCreatedAt()).isNull();
            assertThat(user.getUpdatedAt()).isNull();
        }
    }

    // =========================================================================
    @Nested
    @DisplayName("toProfileResponse — User → UserProfileResponse")
    class ToProfileResponse {

        private User buildUser() {
            return User.builder()
                    .username("john_doe")
                    .email("john@example.com")
                    .passwordHash("$2a$10$BCryptHashThatShouldNeverAppearInResponse")
                    .role(UserRole.USER)
                    .isActive(true)
                    .build();
        }

        @Test
        @DisplayName("maps all public fields correctly")
        void mapsAllPublicFields() {
            User user = buildUser();
            // Simulate what JPA would set after persist
            Instant created = Instant.parse("2024-01-15T10:30:00Z");
            user.setCreatedAt(created);

            UserProfileResponse response = mapper.toProfileResponse(user);

            assertThat(response.username()).isEqualTo("john_doe");
            assertThat(response.email()).isEqualTo("john@example.com");
            assertThat(response.role()).isEqualTo(UserRole.USER);
            assertThat(response.isActive()).isTrue();
            assertThat(response.createdAt()).isEqualTo(created);
        }

        /**
         * Structural test: UserProfileResponse has no passwordHash field.
         * This test documents the intent explicitly and will fail at compile time
         * if someone adds passwordHash to the response record.
         */
        @Test
        @DisplayName("SECURITY: UserProfileResponse has no passwordHash field")
        void response_hasNoPasswordHashField() {
            User user = buildUser();

            UserProfileResponse response = mapper.toProfileResponse(user);

            // Verify by checking every field on the record — none should contain the hash value
            assertThat(response.username()).doesNotContain("$2a$10$");
            assertThat(response.email()).doesNotContain("$2a$10$");
            // If passwordHash were somehow leaked as a String field, one of the above would catch it
            // The real guard is that UserProfileResponse record simply has no such field
        }

        @Test
        @DisplayName("maps UUID id correctly")
        void mapsId() {
            User user = buildUser();
            UUID fixedId = UUID.fromString("550e8400-e29b-41d4-a716-446655440000");
            user.setId(fixedId);

            UserProfileResponse response = mapper.toProfileResponse(user);

            assertThat(response.id()).isEqualTo(fixedId);
        }

        @Test
        @DisplayName("maps ADMIN role correctly")
        void mapsAdminRole() {
            User admin = buildUser();
            admin.setRole(UserRole.ADMIN);

            UserProfileResponse response = mapper.toProfileResponse(admin);

            assertThat(response.role()).isEqualTo(UserRole.ADMIN);
        }

        @Test
        @DisplayName("maps isActive=false for deactivated user")
        void mapsInactiveUser() {
            User user = buildUser();
            user.setIsActive(false);

            UserProfileResponse response = mapper.toProfileResponse(user);

            assertThat(response.isActive()).isFalse();
        }

        @Test
        @DisplayName("maps null createdAt without throwing — pre-persist state")
        void handlesNullCreatedAt() {
            User user = buildUser();
            // createdAt is null before JPA persist
            assertThat(user.getCreatedAt()).isNull();

            UserProfileResponse response = mapper.toProfileResponse(user);

            assertThat(response.createdAt()).isNull();
        }
    }
}
