package com.justrocketscience.auth.mapper;

import com.justrocketscience.auth.dto.request.RegisterRequest;
import com.justrocketscience.auth.dto.response.UserProfileResponse;
import com.justrocketscience.auth.entity.User;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.ReportingPolicy;

/**
 * MapStruct mapper between {@link User} entity and its DTOs.
 *
 * <h3>Why MapStruct over manual mapping</h3>
 * MapStruct generates compile-time bytecode — no reflection at runtime.
 * Mismatched field names or types cause compile errors, not silent null fields
 * in production. For a security-sensitive mapping like "entity → response
 * that must never include passwordHash", a compile-time guarantee is essential.
 *
 * <h3>componentModel = "spring"</h3>
 * Generates a Spring {@code @Component} implementation. The mapper is injected
 * via {@code @Autowired} (or constructor injection) in services and controllers.
 * No manual {@code Mappers.getMapper()} calls needed.
 *
 * <h3>unmappedTargetPolicy = ReportingPolicy.ERROR</h3>
 * Any target field that has no source mapping causes a compile error.
 * This is intentionally strict — it forces every field to be either:
 * <ul>
 *   <li>Explicitly mapped (via @Mapping source=)</li>
 *   <li>Explicitly ignored (via @Mapping ignore=true)</li>
 *   <li>Assigned by MapStruct's name-matching heuristic (documented in Javadoc)</li>
 * </ul>
 * Without this, MapStruct silently leaves unmapped fields as null/default,
 * which would silently expose passwordHash as null in responses rather than
 * failing visibly at compile time.
 *
 * <h3>Lombok + MapStruct ordering</h3>
 * The root pom.xml annotation processor order must be:
 * {@code lombok-mapstruct-binding → lombok → mapstruct-processor}
 * Lombok generates getters/setters first; MapStruct reads them to build the mapping.
 * Wrong order produces "no property named X" compile errors.
 */
@Mapper(
        componentModel = MappingConstants.ComponentModel.SPRING,
        unmappedTargetPolicy = ReportingPolicy.ERROR
)
public interface UserMapper {

    // =========================================================================
    // RegisterRequest → User (entity creation)
    // =========================================================================

    /**
     * Maps a {@link RegisterRequest} to a new {@link User} entity.
     *
     * <p>Fields handled by the service layer, NOT by this mapper:
     * <ul>
     *   <li>{@code passwordHash} — BCrypt encoding happens in {@code AuthService.register()}
     *       before this mapper is called. The mapper receives the already-encoded hash
     *       via a separate {@code user.setPasswordHash(encodedPassword)} call.
     *       It is explicitly ignored here so MapStruct doesn't try to map
     *       {@code request.password()} → {@code entity.passwordHash} and
     *       accidentally bypass encoding.</li>
     *   <li>{@code id} — generated by PostgreSQL (gen_random_uuid()). Never set by application code.</li>
     *   <li>{@code role} — defaults to {@code UserRole.USER} via {@code @Builder.Default}.
     *       Mappers must not decide roles — that's a business rule owned by the service.</li>
     *   <li>{@code isActive} — defaults to {@code true} via {@code @Builder.Default}.</li>
     *   <li>{@code createdAt} / {@code updatedAt} — set by JPA lifecycle callbacks
     *       ({@code @PrePersist} / {@code @PreUpdate}) on the entity.</li>
     * </ul>
     *
     * <h3>Mapping: request.password() is NOT mapped to entity.passwordHash()</h3>
     * This is the most security-critical mapping decision in the entire service.
     * {@code ignore = true} on {@code passwordHash} means MapStruct will not
     * touch that field. The service sets it explicitly after encoding:
     * <pre>
     *   User user = userMapper.toEntity(request);
     *   user.setPasswordHash(passwordEncoder.encode(request.password()));
     * </pre>
     * If a future developer adds a {@code password} field to the entity by mistake,
     * {@code unmappedTargetPolicy = ERROR} will surface it as a compile error
     * rather than silently mapping the plaintext password into the wrong field.
     *
     * @param request the validated registration DTO from the controller
     * @return a partially populated {@link User} entity (passwordHash is null until set by service)
     */
    @Mapping(target = "id",           ignore = true)
    @Mapping(target = "passwordHash", ignore = true)  // SECURITY: BCrypt encoding is service responsibility
    @Mapping(target = "role",         ignore = true)  // Defaults to USER via @Builder.Default
    @Mapping(target = "isActive",     ignore = true)  // Defaults to true via @Builder.Default
    @Mapping(target = "createdAt",    ignore = true)  // Set by @PrePersist
    @Mapping(target = "updatedAt",    ignore = true)  // Set by @PrePersist
    // username → username : matched by name (no @Mapping needed)
    // email    → email    : matched by name (no @Mapping needed)
    User toEntity(RegisterRequest request);

    // =========================================================================
    // User → UserProfileResponse (safe projection)
    // =========================================================================

    /**
     * Maps a {@link User} entity to a {@link UserProfileResponse} DTO.
     *
     * <p>This mapping is the primary security boundary between the persistence
     * layer and the API response. Every entity field that must NOT appear in
     * the response is handled here:
     *
     * <ul>
     *   <li>{@code passwordHash} — not a field on {@link UserProfileResponse}.
     *       Since it doesn't exist on the target record, MapStruct won't map it.
     *       However, if someone adds it to the record by mistake, the compiler
     *       will demand an explicit mapping for it, catching the leak immediately.</li>
     *   <li>{@code updatedAt} — internal audit field, absent from the response record.</li>
     * </ul>
     *
     * <h3>Field-by-field mapping decisions</h3>
     * <ul>
     *   <li>{@code id → id} — direct UUID-to-UUID; no conversion needed.</li>
     *   <li>{@code username → username} — name match; direct String-to-String.</li>
     *   <li>{@code email → email} — name match; direct String-to-String.</li>
     *   <li>{@code role → role} — name match; UserRole enum-to-enum; same type.</li>
     *   <li>{@code isActive → isActive} — name match; Boolean-to-Boolean.
     *       Jackson serializes this as {@code "is_active"} via @JsonProperty on the record.</li>
     *   <li>{@code createdAt → createdAt} — name match; Instant-to-Instant.
     *       Jackson serializes as ISO-8601 via JavaTimeModule.</li>
     * </ul>
     *
     * <p>All six target fields match by name and type. No @Mapping annotation needed.
     * If the record gains a new field, {@code unmappedTargetPolicy = ERROR} ensures
     * the developer must consciously decide how to populate it.
     *
     * @param user the fully-loaded entity from the repository
     * @return a safe, serializable projection with no sensitive fields
     */
    UserProfileResponse toProfileResponse(User user);

    // =========================================================================
    // Partial update helper (for future PATCH endpoints)
    // =========================================================================

    /**
     * Merges non-null fields from a source DTO onto an existing entity.
     * Not used in Week 1 auth flows — added here to establish the pattern
     * for future PATCH /auth/profile endpoints.
     *
     * <p>{@code @BeanMapping(nullValuePropertyMappingStrategy = IGNORE)} tells
     * MapStruct to skip any source field that is null, leaving the target's
     * existing value intact. This is the correct behaviour for a PATCH
     * (partial update) as opposed to a PUT (full replacement).
     *
     * <p>Sensitive and immutable fields are always ignored:
     * <ul>
     *   <li>{@code id} — primary key, never updated</li>
     *   <li>{@code email} — requires a separate email-change + verification flow</li>
     *   <li>{@code passwordHash} — requires a separate changePassword flow</li>
     *   <li>{@code role} — requires admin-only updateRole flow</li>
     *   <li>{@code isActive} — requires admin-only deactivate flow</li>
     *   <li>{@code createdAt} — immutable audit field</li>
     *   <li>{@code updatedAt} — managed by @PreUpdate on the entity</li>
     * </ul>
     *
     * @param source a DTO carrying partial update fields (nulls = no change)
     * @param target the managed entity instance to update in-place
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id",           ignore = true)
    @Mapping(target = "email",        ignore = true)
    @Mapping(target = "passwordHash", ignore = true)
    @Mapping(target = "role",         ignore = true)
    @Mapping(target = "isActive",     ignore = true)
    @Mapping(target = "createdAt",    ignore = true)
    @Mapping(target = "updatedAt",    ignore = true)
    void partialUpdate(RegisterRequest source, @MappingTarget User target);
}
