package com.jrs.rocketservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Lightweight agency representation for list endpoints.
 *
 * Used by: GET /agencies
 * Not used by: GET /agencies/{id}  (uses AgencyResponse instead)
 *
 * Intentionally omits description and website — those fields are long and
 * not useful when scanning a list. The full details are one click away at
 * GET /agencies/{id}.
 *
 * Java record: all fields are final, constructor is auto-generated,
 * equals/hashCode/toString are auto-generated by the compiler.
 * No Lombok needed.
 */
public record AgencySummaryResponse(

        Long id,

        String name,

        String country,

        /**
         * Maps to founded_year in the database.
         * @JsonProperty ensures the JSON key is "foundedYear" (camelCase),
         * regardless of any global ObjectMapper naming strategy configured
         * elsewhere in the application.
         */
        @JsonProperty("foundedYear")
        Integer foundedYear,

        /**
         * URL of the agency logo image.
         * Null is serialized as JSON null — not omitted.
         * Consumers can check for null and render a placeholder.
         */
        @JsonProperty("logoUrl")
        String logoUrl
) {}
